### ISSUE TITLE
[Feature Request] Provide integration with WordPress Command Line Interface WP-CLI

### ISSUE THREAD

**Issue by Pcosta88** [Yoast/License-Manager#146] opened 2018-11-20 18:01 UTC
While users can use Composer to install the plugin https://kb.yoast.com/kb/how-to-install-yoast-plugins-using-composer/

Developers also use WP-CLI: https://wp-cli.org/

Providing integration with WP-CLI will give developers and our users another way to install Yoast.

**Comment by Pcosta88** [comment] 2018-11-20 18:02
Please inform the customer of conversation # 445675 when this conversation has been closed.

**Comment by tacoverdo** [comment] 2018-11-20 20:19
I'm not sure I understand the request here. Why do you think developers can't use WP-CLI now? How are they different from "regular" users? Can you please clarify?

**Comment by Pcosta88** [comment] 2018-11-20 20:33
@tacoverdo Is WP-CLI a different program than Composer?

If so, we should provide a way for users to use WP-CLI in an efficient manner

**Comment by tacoverdo** [comment] 2018-11-22 10:51
WP-CLI is not the same as Composer.

If WP-CLI is installed on the server, devs/devops/admins can already use `wp plugin install wordpress-seo` to install Yoast SEO. (see [documentation](https://developer.wordpress.org/cli/commands/plugin/install/))

**Comment by amboutwe** [comment] 2019-04-02 22:52
WP-CLI can update plugins using `wp plugin update` covered [here](https://developer.wordpress.org/cli/commands/plugin/update/).

In my local tests, I cannot get WP-CLI to recognize that the premium versions shows as needing an update.

_Note_: I was able to update Yoast SEO Premium one time using WP-CLI when it was the only plugin installed but I can't reproduce it now by downgrading and trying again.

Related:
This states that premium plugins/themes must add some additional stuff to the database to make updates available through WP-CLI.
https://github.com/wp-cli/wp-cli/issues/1662
https://wpremote.com/support-center/integrating-wp-remote/adding-wp-remote-support-premium-theme-plugin/

![Selection_440](https://user-images.githubusercontent.com/8060612/55441172-1d1dde80-5567-11e9-9deb-aad5f7da5350.png)
![Selection_441](https://user-images.githubusercontent.com/8060612/55441180-2018cf00-5567-11e9-8a07-7ee7ce5edfe7.png)

**Comment by amboutwe** [comment] 2019-04-02 22:58
Please inform the customer of conversation # 489868 when this conversation has been closed.

**Comment by iamazik** [comment] 2022-10-28 10:20
Closing the issue as it seems no longer relevant anymore.
1. Yoast premium plugins can now update through WP-CLI when there's an update notice in the dashboard.
2. When the premium plugins update notice appear in the WP-CLI, it depends on the WordPress and WP-CLI itself.

**Closed by iamazik** 2022-10-28 10:20 UTC
Labels: support
